[package]
name = "catcount"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
